export type LoanType = '담보' | '전세' | '신용' | '사업자';

export interface LoanProduct {
  id: number;
  bank: string;
  bankCode: string;             // 은행 식별 코드
  productName: string;
  type: LoanType;
  minRate: number;              // 최저 금리 (%)
  maxRate: number;              // 최고 금리 (%)
  maxAmount: number;            // 최대 한도 (만원)
  minAmount: number;            // 최소 한도 (만원)
  termMonths: number[];         // 대출 기간 옵션 (개월)
  features: string[];           // 특징 태그
  badge?: string;               // 추천/인기 뱃지
  description: string;
}

export const DUMMY_LOAN_PRODUCTS: LoanProduct[] = [
  // ─── 담보대출 ───────────────────────────────────────────────────────────────
  {
    id: 1,
    bank: '국민은행',
    bankCode: 'kb',
    productName: 'KB 주택담보대출',
    type: '담보',
    minRate: 3.5, maxRate: 5.2,
    minAmount: 1000, maxAmount: 500000,
    termMonths: [120, 180, 240, 300, 360],
    features: ['고정금리선택', '중도상환수수료없음', '인터넷신청가능'],
    badge: '인기',
    description: '아파트·연립·단독주택 담보. KB 대표 주택담보 상품.',
  },
  {
    id: 2,
    bank: '신한은행',
    bankCode: 'shinhan',
    productName: '신한 아파트론',
    type: '담보',
    minRate: 3.4, maxRate: 5.0,
    minAmount: 2000, maxAmount: 700000,
    termMonths: [120, 180, 240, 360],
    features: ['변동금리', '원리금균등', '비대면신청'],
    badge: '추천',
    description: '아파트 전용 담보대출. 온라인 신청 시 금리 우대.',
  },
  {
    id: 3,
    bank: '우리은행',
    bankCode: 'woori',
    productName: '우리 위비론',
    type: '담보',
    minRate: 3.6, maxRate: 5.4,
    minAmount: 1000, maxAmount: 450000,
    termMonths: [120, 240, 360],
    features: ['고정/변동선택', '부분상환가능'],
    description: '위비 앱을 통한 비대면 담보대출.',
  },
  {
    id: 4,
    bank: '하나은행',
    bankCode: 'hana',
    productName: '하나 원큐 주택론',
    type: '담보',
    minRate: 3.45, maxRate: 5.1,
    minAmount: 1000, maxAmount: 600000,
    termMonths: [120, 180, 240, 300, 360],
    features: ['비대면', '금리우대', '원큐앱연동'],
    badge: '인기',
    description: '하나원큐 앱 전용 주택담보 상품. 금리 우대 혜택.',
  },
  {
    id: 5,
    bank: '농협은행',
    bankCode: 'nh',
    productName: 'NH 올원 담보대출',
    type: '담보',
    minRate: 3.55, maxRate: 5.3,
    minAmount: 500, maxAmount: 400000,
    termMonths: [60, 120, 240, 360],
    features: ['농촌지역우대', '조합원우대'],
    description: 'NH농협 올원뱅크 연동 담보대출.',
  },

  // ─── 전세대출 ───────────────────────────────────────────────────────────────
  {
    id: 6,
    bank: '국민은행',
    bankCode: 'kb',
    productName: 'KB 전세자금대출',
    type: '전세',
    minRate: 2.9, maxRate: 4.5,
    minAmount: 500, maxAmount: 200000,
    termMonths: [12, 24],
    features: ['보증서대출', '연장가능', '임차보증금90%'],
    badge: '인기',
    description: 'HUG·HF·SGI 보증서 활용. 임차보증금의 최대 90%.',
  },
  {
    id: 7,
    bank: '신한은행',
    bankCode: 'shinhan',
    productName: '신한 쏠 전세론',
    type: '전세',
    minRate: 2.85, maxRate: 4.3,
    minAmount: 300, maxAmount: 250000,
    termMonths: [12, 24],
    features: ['비대면신청', '당일심사', '보증서지원'],
    badge: '추천',
    description: '신한SOL 앱 신청. 당일 심사 완료.',
  },
  {
    id: 8,
    bank: '우리은행',
    bankCode: 'woori',
    productName: '우리 전세론',
    type: '전세',
    minRate: 3.0, maxRate: 4.6,
    minAmount: 500, maxAmount: 180000,
    termMonths: [24],
    features: ['HUG보증', '연장2회가능'],
    description: '우리은행 전세보증 대출. 연장 최대 2회.',
  },
  {
    id: 9,
    bank: '카카오뱅크',
    bankCode: 'kakao',
    productName: '카카오뱅크 전월세보증금대출',
    type: '전세',
    minRate: 2.8, maxRate: 4.2,
    minAmount: 300, maxAmount: 150000,
    termMonths: [12, 24],
    features: ['100%비대면', '빠른심사', '카카오앱연동'],
    badge: '인기',
    description: '카카오앱에서 10분 신청. 보증금의 80%까지.',
  },
  {
    id: 10,
    bank: '케이뱅크',
    bankCode: 'kbank',
    productName: '케이뱅크 전세대출',
    type: '전세',
    minRate: 2.9, maxRate: 4.4,
    minAmount: 300, maxAmount: 120000,
    termMonths: [12, 24],
    features: ['비대면', 'SGI보증', '우대금리적용'],
    description: '케이뱅크 앱 전용 전세자금 대출.',
  },

  // ─── 신용대출 ───────────────────────────────────────────────────────────────
  {
    id: 11,
    bank: '카카오뱅크',
    bankCode: 'kakao',
    productName: '카카오뱅크 신용대출',
    type: '신용',
    minRate: 4.5, maxRate: 8.9,
    minAmount: 100, maxAmount: 30000,
    termMonths: [12, 24, 36],
    features: ['비대면', '빠른한도조회', '연체이자없음'],
    badge: '인기',
    description: '신용점수에 따라 최대 3억. 카카오앱에서 즉시 신청.',
  },
  {
    id: 12,
    bank: '토스뱅크',
    bankCode: 'toss',
    productName: '토스뱅크 신용대출',
    type: '신용',
    minRate: 4.2, maxRate: 9.5,
    minAmount: 100, maxAmount: 25000,
    termMonths: [12, 24, 36, 48],
    features: ['비대면', '실시간대출', '토스앱연동'],
    badge: '추천',
    description: '토스앱에서 5분 내 대출 완료. 마이너스통장 옵션.',
  },
  {
    id: 13,
    bank: '국민은행',
    bankCode: 'kb',
    productName: 'KB 직장인 신용대출',
    type: '신용',
    minRate: 4.0, maxRate: 7.8,
    minAmount: 300, maxAmount: 20000,
    termMonths: [12, 24, 36],
    features: ['직장인전용', '급여이체우대', '금리우대'],
    description: '급여 이체 고객 금리 우대. 직장인 전용 신용대출.',
  },
  {
    id: 14,
    bank: '하나은행',
    bankCode: 'hana',
    productName: '하나 원큐 신용대출',
    type: '신용',
    minRate: 4.3, maxRate: 8.5,
    minAmount: 100, maxAmount: 20000,
    termMonths: [12, 24, 36],
    features: ['비대면', '하나원큐앱', '한도조회무료'],
    description: '원큐앱 전용. 한도 조회 시 신용점수 영향 없음.',
  },
  {
    id: 15,
    bank: '신한은행',
    bankCode: 'shinhan',
    productName: '신한 마이카드론',
    type: '신용',
    minRate: 5.0, maxRate: 10.0,
    minAmount: 50, maxAmount: 10000,
    termMonths: [6, 12, 24],
    features: ['카드실적우대', '신용평가우대'],
    description: '신한카드 실적 기반 신용 우대 대출.',
  },

  // ─── 사업자대출 ─────────────────────────────────────────────────────────────
  {
    id: 16,
    bank: '기업은행',
    bankCode: 'ibk',
    productName: 'IBK 사업자 운전자금대출',
    type: '사업자',
    minRate: 4.8, maxRate: 9.0,
    minAmount: 500, maxAmount: 50000,
    termMonths: [12, 24, 36],
    features: ['개인사업자가능', '운전자금지원', '보증서대출'],
    badge: '추천',
    description: '소상공인·중소기업 운전자금. 보증서 활용 저금리.',
  },
  {
    id: 17,
    bank: '국민은행',
    bankCode: 'kb',
    productName: 'KB 소상공인 대출',
    type: '사업자',
    minRate: 4.5, maxRate: 8.5,
    minAmount: 300, maxAmount: 30000,
    termMonths: [12, 24, 36],
    features: ['소상공인전용', '신보보증', '저금리'],
    badge: '인기',
    description: '신용보증재단 연계 소상공인 전용 대출.',
  },
  {
    id: 18,
    bank: '신한은행',
    bankCode: 'shinhan',
    productName: '신한 비즈 사업자대출',
    type: '사업자',
    minRate: 4.6, maxRate: 8.8,
    minAmount: 500, maxAmount: 50000,
    termMonths: [12, 24, 36, 48],
    features: ['법인가능', '시설자금지원', '세금우대'],
    description: '법인·개인사업자 모두 가능. 시설자금 포함.',
  },
  {
    id: 19,
    bank: '우리은행',
    bankCode: 'woori',
    productName: '우리 창업기업 대출',
    type: '사업자',
    minRate: 5.0, maxRate: 9.5,
    minAmount: 300, maxAmount: 20000,
    termMonths: [12, 24, 36],
    features: ['창업5년이내', '기술보증연계', '초기기업지원'],
    description: '창업 5년 이내 기업 특화. 기보 연계 저금리.',
  },
  {
    id: 20,
    bank: '농협은행',
    bankCode: 'nh',
    productName: 'NH 농업인 사업자대출',
    type: '사업자',
    minRate: 3.5, maxRate: 7.0,
    minAmount: 200, maxAmount: 30000,
    termMonths: [12, 24, 36, 60],
    features: ['농업인우대', '농축협연계', '저금리'],
    badge: '추천',
    description: '농업인·영농법인 전용. 농신보 보증 연계 최저금리.',
  },
];

export function filterLoanProducts(type?: LoanType, bankCode?: string): LoanProduct[] {
  let list = [...DUMMY_LOAN_PRODUCTS];
  if (type) list = list.filter(p => p.type === type);
  if (bankCode) list = list.filter(p => p.bankCode === bankCode);
  return list.sort((a, b) => a.minRate - b.minRate);
}
